// Verification uses public WebGL inspection of the BUILT shader, no library internals.
export function compareSeams(){
 const tiles=[...waterGLAudit.tiles.values()];waterGLAudit.capture=false;
 const gl=tiles[0].gl,original={fb:gl.getParameter(gl.FRAMEBUFFER_BINDING),program:gl.getParameter(gl.CURRENT_PROGRAM),vao:gl.getParameter(gl.VERTEX_ARRAY_BINDING),viewport:gl.getParameter(gl.VIEWPORT),active:gl.getParameter(gl.ACTIVE_TEXTURE),clear:gl.getParameter(gl.COLOR_CLEAR_VALUE),blend:gl.isEnabled(gl.BLEND),depth:gl.isEnabled(gl.DEPTH_TEST),scissor:gl.isEnabled(gl.SCISSOR_TEST)};
 const oldTextures=[];for(let i=0;i<3;i++){gl.activeTexture(gl.TEXTURE0+i);oldTextures.push(gl.getParameter(gl.TEXTURE_BINDING_2D));}
 const fragment=gl.getAttachedShaders(tiles[0].program).map(s=>gl.getShaderSource(s)).find(s=>s.includes('flowingSlope'));
 const p=gl.createProgram(),shaders=[];
 for(const [type,source]of[[gl.VERTEX_SHADER,'#version 300 es\nprecision highp float;uniform vec2 uProbeUV;out vec2 vUV;out vec3 vViewPosition;void main(){vec2 q=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(q*2.0-1.0,0,1);vUV=uProbeUV;vViewPosition=vec3(0,0,-1000);}'],[gl.FRAGMENT_SHADER,fragment]]){const s=gl.createShader(type);shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));
 const fb=gl.createFramebuffer(),color=gl.createTexture(),vao=gl.createVertexArray();gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,color);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,color,0);gl.viewport(0,0,1,1);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST);gl.bindVertexArray(vao);gl.useProgram(p);
 const loc=name=>gl.getUniformLocation(p,name);
 for(const name of ['uMagnitudeMax','uWaves','uAdvection','uWaterColor','uHighlights','uBrightness','uEastView','uNorthView','uUpView','uLightView','uDiffuse','uAmbient']){const v=tiles[0].uniforms[name];if(typeof v==='number')gl.uniform1f(loc(name),v);else gl[`uniform${v.length}fv`](loc(name),v);}
 gl.uniform1i(loc('uVelocity'),0);gl.uniform1i(loc('uWaterMask'),1);gl.uniform1f(loc('uFade'),1);
 const pixel=new Uint8Array(4);let samples=0,maxRGBAError=0,timeVarying=0;
 function sample(tile,uv,time){gl.uniform2fv(loc('uProbeUV'),uv);gl.uniform1f(loc('uTime'),time);for(const name of ['uWorldOffset','uSizeMeters','uVelocityUV','uFootprintUV'])gl[`uniform${tile.uniforms[name].length}fv`](loc(name),tile.uniforms[name]);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tile.velocity);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,tile.footprint);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);return Array.from(pixel);}
 for(const a of tiles)for(const [dx,dy]of[[1,0],[0,1]]){const o=a.uniforms.uWorldOffset,s=a.uniforms.uSizeMeters,b=tiles.find(t=>t.uniforms.uWorldOffset[0]===o[0]+dx*s[0]&&t.uniforms.uWorldOffset[1]===o[1]+dy*s[1]);if(!b)continue;
 for(let k=1;k<32;k++){const u=dx?[1,k/32]:[k/32,1],v=dx?[0,k/32]:[k/32,0],early=sample(a,u,.65);if(!early[3])continue;for(const time of [.65,.75,4.799,4.801]){const aa=sample(a,u,time),bb=sample(b,v,time);samples++;maxRGBAError=Math.max(maxRGBAError,...aa.map((x,i)=>Math.abs(x-bb[i])));if(aa.some((x,i)=>x!==early[i]))timeVarying++;}}}
 const glError=gl.getError();gl.bindFramebuffer(gl.FRAMEBUFFER,original.fb);gl.bindVertexArray(original.vao);gl.useProgram(original.program);gl.viewport(...original.viewport);gl.clearColor(...original.clear);for(const [flag,on]of[[gl.BLEND,original.blend],[gl.DEPTH_TEST,original.depth],[gl.SCISSOR_TEST,original.scissor]])on?gl.enable(flag):gl.disable(flag);for(let i=0;i<3;i++){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,oldTextures[i]);}gl.activeTexture(original.active);gl.deleteFramebuffer(fb);gl.deleteTexture(color);gl.deleteVertexArray(vao);gl.deleteProgram(p);for(const s of shaders)gl.deleteShader(s);waterGLAudit.tiles.clear();minimalHost.water.setParameters({paused:true});return {samples,maxRGBAError,timeVarying,glError};
}
